<?php
// This ist Pop Template for Magento.

// get all variables
$trigger = $this->getData('trigger');
$exitintent_delay = $this->getData('exitintent_delay');
$inactivity_delay = $this->getData('inactivity_delay');
$scrolldepth = $this->getData('scrolldepth');
$timeonpage = $this->getData('timeonpage');
$title = $this->getData('title');
$message = $this->getData('message');
$coupon = $this->getData('coupon');
$coupon_code = $this->getData('coupon_code');
$subscription = $this->getData('subscription');
$subscription_provider = $this->getData('subscription_provider');
$subscription_link = $this->getData('subscription_link');
$button = $this->getData('button');
$button_text = $this->getData('button_text');
$button_link = $this->getData('button_link');
$cmsblock = $this->getData('cmsblock');
$help = $this->getData('help');
$phone = $this->getData('phone');
$email = $this->getData('email');
$chat = $this->getData('chat');
$skype = $this->getData('skype');
$whatsapp = $this->getData('whatsapp');
$template = $this->getData('template');

echo $trigger.'<br>';
echo $exitintent_delay.'<br>';
echo $inactivity_delay.'<br>';
echo $scrolldepth.'<br>';
echo $timeonpage.'<br>';
echo $title.'<br>';
echo $message.'<br>';
echo $coupon.'<br>';
echo $coupon_code.'<br>';
echo 'Subscription: '.$subscription.'<br>';
echo 'subscription_provider: '.$subscription_provider.'<br>';
echo $subscription_link.'<br>';
echo $button.'<br>';
echo $button_text.'<br>';
echo $button_link.'<br>';
echo $cmsblock.'<br>';
echo $help.'<br>';
echo $phone.'<br>';
echo $email.'<br>';
echo $chat.'<br>';
echo $skype.'<br>';
echo $whatsapp.'<br>';
echo $template.'<br>';

if($trigger=="exitintent") {
    $triggerdata = "popup-trigger=\"".$trigger."\"";
    $parameters = "popup-time=\"".$exitintent_delay."\"";

}
if($trigger=="scrolldepth") {
    $triggerdata = "popup-trigger=\"".$trigger."\"";
    $parameters = "popup-scrolldepth=\"".$scrolldepth."\"";
}
if($trigger=="inactivity") {
    $triggerdata = "popup-trigger=\"".$trigger."\"";
    $parameters = "popup-time=\"".$inactivity_delay."\"";
}
if($trigger=="timeonpage") {
    $triggerdata = "popup-trigger=\"".$trigger."\"";
    $parameters = "popup-time=\"".$timeonpage."\"";
}
?>

<button id="myBtn">Open Modal</button>
<div id="shadowbox" class="shadowbox" <?php echo $triggerdata.' '.$parameters ?> >
    <div id="magepopup" class="magepopup <?php echo $trigger ?>">
        <span id="close" class="close">X</span>
        <?php if($cmsblock) : ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($cmsblock)->toHtml() ?>
        <?php else : ?>
            <?php if($title) : ?> <div class="title"><?php echo $title ?></div> <?php endif; ?>
            <?php if($message) : ?> <div class="message"><?php echo $message ?></div> <?php endif; ?>
            <?php if($coupon) : ?> <div class="coupon"><input value="<?php echo $coupon_code ?>" readonly><button class="button emailcopybtn">Copy</button></div> <?php endif; ?>
            <?php if($subscription) : ?>
                <div class="newsletter">
                    <?php if($subscription_provider=="magento") : ?>
                        <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('webmasterei/magepopups/subscribe.phtml')->toHtml(); ?>
                    <?php elseif($subscription_provider=="cleverreach") : ?>
                        <form class="layout_form cr_form cr_font" action="<?php echo $subscription_link ?>wcs/" method="post" target="_blank">
                            <div class="cr_body cr_page cr_font formbox">
                                <div class="input-box">
                                    <label for="" class="itemname">E-Mail*</label> <input name="email" value="" type="text" class="input-text required-entry validate-email" />
                                    <button type="submit" class="button"><?php echo $this->__('Subscribe') ?> </button>
                                </div>
                            </div>

                        </form>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <?php if($button) : ?>
                <a class="button popupbutton" href="<?php echo $button_link ?>"><?php echo $button_text ?></a>
            <?php endif; ?>
            <?php if($help) : ?>
                <dl class="phone">
                    <dt><?php echo $this->__('Call us: ') ?></dt>
                    <dd><a href="tel:<?php echo preg_replace("/^0/", "+49" ,$phone ); ?>"><?php echo $phone ?></a></dd>
                </dl>
                <ul class="help-col">
                    <li><a class="button" href="<?php echo $email ?>"><?php echo $this->__('E-Mail') ?></a></li>
                    <li><a class="button" href="<?php echo $chat ?>">Chat</a></li>
                    <li><a class="button" href="skype:<?php echo $skype; ?>?call" onclick="Skype.tryAnalyzeSkypeUri('call', '0');"><?php echo $this->__('Skype') ?></a></li>
                </ul>
                <div class="clearfix"></div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<button id="deletecookie">Delete Cookie</button>
<script>
    /* Development Stuff */
    jQuery(document).ready( function($){
        console.log(Cookies.get('popup'));

        $('#deletecookie').click( function() {
            Cookies.remove('popup');
        });
    });


</script>
<?php if($trigger=="exitintent") : ?>
<script>
    jQuery( document ).ready(function($) {
        var cookie = Cookies.get('popup')
        var opened = 0;
        if(!cookie) {
                $( document ).on( "mousemove", function( event ) {
                    if(event.pageY < 10 && opened==0) {
                        setTimeout(function() {
                            $('#shadowbox').fadeIn();
                        },<?php echo $exitintent_delay ?>);
                        opened = 1;
                        console.log(opened);
                    }
            });
        }
        $('#close').click(function(){
            Cookies.set('popup', 'closed' , {expires:7});
        });
    });
</script>
<?php endif; ?>
<?php if($trigger=='scrolldepth') : ?>
    <script>
        jQuery( document ).ready(function($) {
            var height = $(document).height()-$(window).height();
            var scrolldepth = 0;
            var toTop = 0;
            var opened = 0;
            var cookie = Cookies.get('popup')
            $(window).scroll(function(event) {
                toTop = $(window).scrollTop();
                scrolldepth = toTop/height;
                console.log(scrolldepth);
                if(scrolldepth ><?php echo $scrolldepth/100 ?> && opened==0) {
                    if(!cookie) {
                        $('#shadowbox').fadeIn();
                        opened = 1
                    }
                }
            });
            $('#close').click(function(){
                Cookies.set('popup', 'closed' , {expires:7});
            });
        });
    </script>
<?php endif; ?>

<?php if($trigger=="inactivity") : ?>
    <script type="text/javascript">
        jQuery(document).ready(function($){
            var cookie = Cookies.get('popup');
            idleTime = 0;
            var opened = 0;
            var idleInterval = setInterval(timerIncrement, 1000);
            function timerIncrement()
            {
                idleTime++;
                if (idleTime > <?php echo $inactivity_delay ?>)
                {
                    if(!cookie && opened==0) {
                        $('#shadowbox').fadeIn();
                        opened=1;
                    }
                }
            }
            $(this).mousemove(function(e){
                idleTime = 0;
            });
            $('#close').click(function(){
                Cookies.set('popup', 'closed' , {expires:7});
            });
        })
    </script>
<?php endif; ?>
<?php if($trigger=="timeonpage") : ?>
<script>
    jQuery(document).ready(function($){
        //Cookies.remove('popup');
        var cookie = Cookies.get('popup');
        function showbox(){
            $('#shadowbox').fadeIn();
        }
        var timeout = <?php echo $timeonpage ?>*1000;

        if(!cookie) {
            setTimeout(showbox, timeout);
        }
        $('#close').click(function(){
            Cookies.set('popup', 'closed' , {expires:7});
        });
    })
</script>
<?php endif; ?>
