<?php
// This ist Pop Template for Magento.

// get all variables
$trigger = $this->getData('trigger');
$exitintent_delay = $this->getData('exitintent_delay');
$inactivity_delay = $this->getData('inactivity_delay');
$scrolldepth = $this->getData('scrolldepth');
$timeonpage = $this->getData('timeonpage');
$title = $this->getData('title');
$message = $this->getData('message');
$coupon = $this->getData('coupon');
$coupon_code = $this->getData('coupon_code');
$subscription = $this->getData('scubscription');
$button = $this->getData('button');
$button_text = $this->getData('button_text');
$button_link = $this->getData('button_link');
$cmsblock = $this->getData('cmsblock');
$help = $this->getData('help');
$phone = $this->getData('phone');
$email = $this->getData('email');
$chat = $this->getData('chat');
$skype = $this->getData('skype');
$whatsapp = $this->getData('whatsapp');
$template = $this->getData('template');

echo $trigger.'<br>';
echo $exitintent_delay.'<br>';
echo $inactivity_delay.'<br>';
echo $scrolldepth.'<br>';
echo $timeonpage.'<br>';
echo $title.'<br>';
echo $message.'<br>';
echo $coupon.'<br>';
echo $coupon_code.'<br>';
echo $subscription.'<br>';
echo $button.'<br>';
echo $button_text.'<br>';
echo $button_link.'<br>';
echo $cmsblock.'<br>';
echo $help.'<br>';
echo $phone.'<br>';
echo $email.'<br>';
echo $chat.'<br>';
echo $skype.'<br>';
echo $whatsapp.'<br>';
echo $template.'<br>';
?>
<button id="myBtn">Open Modal</button>
<div id="shadowbox" class="shadowbox">
    <div id="magepopup" class="magepopup <?php echo $trigger ?>">
        <span id="close" class="close">X</span>
        <?php if($title) { ?> <div class="title"><?php echo $title ?></div> <?php } ?>
        <?php if($title) { ?> <div class="message"><?php echo $message ?></div> <?php } ?>
    </div>
</div>

<?php if($trigger=="exitintent") : ?>
<script>
    ouibounce(document.getElementById('shadowbox'), {
        aggressive: true,
        timer: <?php echo $exitintent_delay ?>,
        sitewide: true
    });
</script>
<?php endif; ?>
<?php if($trigger=='scrolldepth') : ?>
    <script>
        jQuery( document ).ready(function($) {
            var height = $(document).height()-$(window).height();
            var scrolldepth = 0;
            var toTop = 0;
            var opened = 0;
            var cookie = Cookies.get('popup')
            $(window).scroll(function(event) {
                toTop = $(window).scrollTop();
                scrolldepth = toTop/height;
                console.log(scrolldepth);
                if(scrolldepth ><?php echo $scrolldepth/100 ?> && opened==0) {
                    if(!cookie) {
                        $('#shadowbox').fadeIn();
                        opened = 1
                    }
                }
            });

            $('#close').click(function(){
                Cookies.set('popup', 'closed');
            });


        });
    </script>
<?php endif; ?>
