<?php
$trigger = $this->getData('trigger');
$exitintent_delay = $this->getData('exitintent_delay');
$inactivity_delay = $this->getData('inactivity_delay');
$scrolldepth = $this->getData('scrolldepth');
$timeonpage = $this->getData('timeonpage');
$urlparameter = $this->getData('url_parameter');
$title = $this->getData('title');
$message = $this->getData('message');
$coupon = $this->getData('coupon');
$coupon_code = $this->getData('coupon_code');
$subscription = $this->getData('subscription');
$subscription_provider = $this->getData('subscription_provider');
$subscription_link = $this->getData('subscription_link');
$button = $this->getData('button');
$button_text = $this->getData('button_text');
$button_link = $this->getData('button_link');
$cmsblock_yesno = $this->getData('cmsblock_yesno');
$cmsblock = $this->getData('cmsblock');
$help = $this->getData('help');
$phone = $this->getData('phone');
$email = $this->getData('email');
$chat = $this->getData('chat');
$skype = $this->getData('skype');
$whatsapp = $this->getData('whatsapp');
$template = $this->getData('template');
$border_color = Mage::getStoreConfig('magepopups/magepopups_blocks/border_color',Mage::app()->getStore());
if(!$border_color) {
    $border_color = "#3399cc";
}
$button_color = Mage::getStoreConfig('magepopups/magepopups_blocks/button_color',Mage::app()->getStore());
$button_hover_color = Mage::getStoreConfig('magepopups/magepopups_blocks/button_hover_color',Mage::app()->getStore());
$button_font_color = Mage::getStoreConfig('magepopups/magepopups_blocks/button_font_color',Mage::app()->getStore());

$columnCount =0;
if($email) {
    $columnCount++;
}
if($chat) {
    $columnCount++;
}
if($skype) {
    $columnCount++;
}

if($trigger=="exitintent") {
    $triggerdata = "trigger=\"".$trigger."\"";
    $parameters = "exitintent_delay=\"".$exitintent_delay."\"";

}
if($trigger=="scrolldepth") {
    $triggerdata = "trigger=\"".$trigger."\"";
    $parameters = "scrolldepth=\"".$scrolldepth."\"";
}
if($trigger=="inactivity") {
    $triggerdata = "trigger=\"".$trigger."\"";
    $parameters = "inactivity_delay=\"".$inactivity_delay."\"";
}
if($trigger=="timeonpage") {
    $triggerdata = "trigger=\"".$trigger."\"";
    $parameters = "timeonpage=\"".$timeonpage."\"";
}
if($trigger=="urlparameter") {
    $triggerdata = "trigger=\"".$trigger."\"";
    $parameters = "parameter=\"".$urlparameter."\"";
}

$widgetId =  preg_replace('/\s+/', '', 'shadowbox'.$trigger);

?>
<script>
    jQuery(document).ready(function($){
        $().magepopups('<?php echo $widgetId; ?>');
    })
</script>
<div id="myDivId" value="100"></div>
<style>
    .magepopup {
        <?php if($border_color) : ?> border-color: <?php echo $border_color; ?> <?php endif; ?>
    }
    .magepopup .button {
       <?php if($button_color) : ?> background-color:<?php echo $button_color; ?>; <?php endif; ?>
    <?php if($button_font_color) : ?> color: <?php echo $button_font_color; ?>;<?php endif; ?>
    }
    .magepopup .button:hover {
        <?php if($button_hover_color) : ?> background-color: <?php echo $button_hover_color; ?>;<?php endif; ?>
    }
</style>
<div id="<?php echo $widgetId ?>" class="shadowbox" <?php echo $triggerdata.' '.$parameters ?> >
    <div id="magepopup" class="magepopup <?php echo $trigger ?>">
        <span id="close" class="close">X</span>
        <?php if($cmsblock_yesno) : ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($cmsblock)->toHtml() ?>
        <?php else : ?>
            <?php if($title) : ?> <div class="title"><?php echo $title ?></div> <?php endif; ?>
            <?php if($message) : ?> <div class="message"><?php echo $message ?></div> <?php endif; ?>
            <?php if($coupon) : ?> <div class="coupon">
                <label for="coupon-code"><?php echo $this->__('Coupon: ') ?></label>
                <input name="coupon-code" value="<?php echo $coupon_code ?>" readonly><button class="button emailcopybtn"><?php echo $this->__('Copy'); ?></button></div> <?php endif; ?>
            <?php if($subscription) : ?>
                <div class="newsletter">
                    <?php if($subscription_provider=="magento") : ?>
                        <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('webmasterei/magepopups/subscribe.phtml')->toHtml(); ?>
                    <?php elseif($subscription_provider=="cleverreach") : ?>
                        <form class="layout_form cr_form cr_font" action="<?php echo $subscription_link ?>wcs/" method="post" target="_blank">
                            <div class="cr_body cr_page cr_font formbox">
                                <div class="input-box">
                                    <label for="" class="itemname">E-Mail*</label> <input name="email" value="" type="text" class="input-text required-entry validate-email" />
                                    <button type="submit" class="button"><?php echo $this->__('Subscribe') ?> </button>
                                </div>
                            </div>
                        </form>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <?php if($button) : ?>
                <a class="button popupbutton" href="<?php echo $button_link ?>"><?php echo $button_text ?></a>
            <?php endif; ?>
            <?php if($help) : ?>
                <?php if($phone) : ?>
                    <dl class="phone">
                        <dt><?php echo $this->__('Call us: ') ?></dt>
                        <dd><a href="tel:<?php echo preg_replace("/^0/", "+49" ,$phone ); ?>"><?php echo $phone ?></a></dd>
                    </dl>
                <?php endif; ?>
                <ul class="help-col col-<?php echo $columnCount; ?>">
                    <?php if($email): ?><li><a class="button" href="<?php echo $email ?>"><?php echo $this->__('E-Mail') ?></a></li><?php endif; ?>
                    <?php if($chat): ?><li><a class="button" href="<?php echo $chat ?>">Chat</a></li><?php endif; ?>
                    <?php if($skype): ?><li><a class="button" href="skype:<?php echo $skype; ?>?call" onclick="Skype.tryAnalyzeSkypeUri('call', '0');"><?php echo $this->__('Skype') ?></a></li><?php endif; ?>
                </ul>
                <div class="clearfix"></div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
